settings = {
    "WIDTH": 200,
    "HEIGHT": 66,
    "CHANNELS": 3,
    "BALANCE_MODE": 'RESAMPLE',
    "DEFAULT_TRAIN_FILE_DIRECTORY": 'D:/train_data/raw/',
    "DEFAULT_TRAIN_FILE": 'D:/train_data/raw/training_data_{}.npy',
    "DEFAULT_TRAIN_FILE_PROCESSED_DIRECTORY": 'D:/train_data/processed/',
    "DEFAULT_TRAIN_FILE_PROCESSED": 'D:/train_data/processed/training_data_processed_{}_{}.npy',
    "LEARNING_RATE": 1e-3,
    "DROPOUT_RATE": 0.5,
    "EPOCHS": 6,
    "VALIDATION_SPLIT": 0.05,
    "BATCH_SIZE": 1000,
    "DEFAULT_MODEL_FILE": 'saved_models/env_junk_with_higher_correction.h5',
    "TARGET_SPEED": 80,
    "CORRECTION": 0.3,
    "TRAINING": False,
    "SAVE_DATA": False,
    "TURNING_SLOW_COEFFICIENT": 0.3,
    "CRUISE_CONTROL_STEEPNESS": 0.7
}
